### ISSUE TITLE
How do I use this exactly?

### ISSUE THREAD

**Issue by Budhvin** [JonasHeim/Civilization-5-Savegame-Editor#4]
I am not the most tech savy but I am interested in being able to convert a mutilplayer save to a singleplayer save. How do I run this program?

**Comment by emmehan** [comment]
Hey,
you can download the executable as a .zip [here](https://github.com/JonasHeim/Civilization-5-Savegame-Editor/releases/tag/v0.0.2). You will find the binary in 
`Civilization-5-Savegame-Editor_v0.0.2.zip\Release`
Or you can go ahead and build the binary by yourself. 

Then just open up a savegame, change the mode and save it.

<img src="https://user-images.githubusercontent.com/18228461/191287176-aead752d-92f1-40b9-a23a-7eba1b414684.png" width=75%>

Then you are able to edit the savestate e.g. via the Ingame Editor mod and revert the mode back to multiplayer afterwards.

On Windows the Steam savegames are usually located in 
`<user>\Documents\My Games\Sid Meier's Civilization 5\Saves`

Make sure to copy the savestates to the correct folders! Multiplayer lobbies can only load savestates located in the **multi** folder, vice versa **single** for Singleplayer lobbies.

**Comment by emmehan** [comment]
Closed.
